### ISSUE TITLE
k5prog for linux don't load calibration file

### ISSUE THREAD

**Issue by iw2evk** [LHunti/Quansheng-UV-Calibrations#3]
Hi,

i've download the calibration file for squelch and attempt to load in radio.
I can't load the file with linux version of k5prog on my ubuntu 20.04
i receive the info 

open error 2 No such file or directory
Open /dev/ttyUSB0 failed

what is the right procedure ?

P.s. why i cant load the file in radio with uvtool web page ?
https://egzumer.github.io/uvtools/

**Comment by LHunti** [comment]
Hi,

sorry for the late answer.

Although I'm not a linux user, it's like if the radio wasn't available. To upload the calibration file, the radio must be switched on in normal mode.

Uvtools is only for writing flash memory, not eeprom.

**Comment by iw2evk** [comment]
Hi

The calibration data are saved in EEPROM or flash?
Thanks
Regards

Il sab 1 giu 2024, 11:14 LHunti ***@***.***> ha scritto:

**Comment by LHunti** [comment]
The radio stores the calibration data in an EEPROM, as well as the saved frequencies.
